# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4ElFVpyrb79Pk5yS1vEJX8VOyD5pYyF
"""

import pandas as pd
import numpy as np
import requests
import pickle
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,accuracy_score
from sklearn.preprocessing import LabelEncoder

'''# Weather Data API (e.g., OpenWeatherMap)
def get_weather_data(api_key, location):https://api.openweathermap.org/data/3.0/onecall?
    url = f"lat={27.3333}&lon={88.6167}&exclude={part}&appid={ff164e0681a3de26c8766138771959f8}"
    response = requests.get(url)
    return response.json()'''

# River Level Data API
def get_river_level_data(api_key, river_station_id):
    url = f"http://api.riverdata.com/station/{river_station_id}?apikey={api_key}"
    response = requests.get(url)
    return response.json()

# Satellite Data (Google Earth Engine or NASA API)
def get_satellite_imagery(api_key, lat, lon, date):
    url = f"https://api.nasa.gov/planetary/earth/imagery?lon={88.6167}&lat={27.3333}&dim=0.1&date={9/26/2024}&api_key={Wi8VD4bZ9PabecSb8cTJYNzenvl3qRV32N6xhOD8}"
    response = requests.get(url)
    return response.json()

data.head()

# Load historical flood data (weather conditions, river levels, and flood status)
data = pd.read_csv('/content/flood_risk_dataset_india.csv')  # CSV containing features: rainfall, river_level, flood (1/0)

# Features and labels
X = data[['Rainfall (mm)', 'Water Level (m)']]
y = data['Flood Occurred']

# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Prediction Accuracy: {accuracy*100:.2f}%")

# Example real-time prediction
def predict_flood(rainfall, river_level):
    return model.predict([[rainfall, river_level]])

print(predict_flood(100,100))

# Save the model using pickle
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)